FROM docker.io/tomcat:9.0.79-jdk21-openjdk

COPY /target/*.war /usr/local/tomcat/webapps/ROOT.war

RUN addgroup  springboot && adduser tomcat
RUN usermod -G springboot tomcat
RUN chown -R tomcat /usr/local/tomcat
USER tomcat

EXPOSE 8080